### ISSUE TITLE
flipped motorcycle 

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#13]

**Comment by commiteth** [comment]
Current balance: 0.000000 ETH
Contract address: [0x90d760651d4f75beab3e55f753f0b324281b0a8c](https://ropsten.etherscan.io/address/0x90d760651d4f75beab3e55f753f0b324281b0a8c)
![QR Code](https://rob-open-bounty.ngrok.io/qr/rcullito/postmarkMitt/bounty/13/46e5f2143db76564ab1ba43ea83639c2ade3609080c68db53b65241ae22277a5/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
