### ISSUE TITLE
hatterberg

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#14]

**Comment by commiteth** [comment]
![Contract deploying](https://rob-open-bounty.ngrok.io/img/deploying_contract.png)
Transaction: [0xa42e2c413723babfc10aa3865ba5f3f5baabd0d174964b5dcd70662ca888835d](https://ropsten.etherscan.io/tx/0xa42e2c413723babfc10aa3865ba5f3f5baabd0d174964b5dcd70662ca888835d)

**Comment by commiteth** [comment]
Current balance: 0.000000 ETH
Contract address: [0x570ff363e5d23cae0f42ff82fafe286327e414e0](https://ropsten.etherscan.io/address/0x570ff363e5d23cae0f42ff82fafe286327e414e0)
![QR Code](https://rob-open-bounty.ngrok.io/qr/rcullito/postmarkMitt/bounty/14/15b0080b5ca06e4525187c8d76c6f71528875e732b80f2c7cff2ac955fd6b93d/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
