### ISSUE TITLE
rip avicii

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#22]

**Comment by commiteth** [comment]
Current balance: 0.000000 ETH
Contract address: [0xdd4444591788793ba89063d53737b6a4029ec6e5](https://ropsten.etherscan.io/address/0xdd4444591788793ba89063d53737b6a4029ec6e5)
![QR Code](https://rob-open-bounty.ngrok.io/qr/rcullito/postmarkMitt/bounty/22/837cf0892b16eab344c9a4a508b5ec77381d2736b9a3f0b13c3892983c3ee3f1/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
