### ISSUE TITLE
yikes 

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#4]

**Comment by commiteth** [comment]
Current balance: 0.000000 ETH
Contract address: [0xb0ab7d3aca6a64130f77772c0a09cad5c3bedba1](https://ropsten.etherscan.io/address/0xb0ab7d3aca6a64130f77772c0a09cad5c3bedba1)
![QR Code](https://rob-open-bounty.ngrok.io/qr/rcullito/postmarkMitt/bounty/4/017dd4252eb09dd7b3e11aa5813b0acb4a8e1e2236010b87bcfa5b9ccca27e2f/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
